{{- define "helm-library.secret.template" -}}
{{- $required := include "helm-library.common.required" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required (printf $required "name") .Values.name | quote }}
  labels:
    {{- include "helm-library.common.labels" . | nindent 4 }}
type: {{ required (printf $required "secret.type") .Values.secret.type | quote }}
data: {}
{{- end }}
{{/* include this */}}
{{- define "helm-library.secret" -}}
{{- include "helm-library.util.merge" (append . "helm-library.secret.template") -}}
{{- end -}}